spring.application.name=openai
spring.main.web-application-type=servlet
spring.ai.openai.chat.options.stream=false
spring.ai.ollama.base-url=http://localhost:11434
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.ollama.chat.model=llama3.2:1b
spring.ai.chat.client.enabled=false
